name: CICD PIPELINe
on:
  push:
   branches:
     - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: run the tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 18
      - name: install dependencies
        run: npm install
      - name: lints
        run: npm run lint
      - name: running the tests
        run: npm test
